from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

import requests

from .models import Platform, ProjectType, SkillGenContext
from .scanner import ProjectScan

# Max bytes to read from any single file to prevent exploding prompts
MAX_FILE_BYTES = 8192




def call_msl_api(messages: list[dict[str, str]], project_root: Optional[Path] = None) -> str:
    """Execute the HTTP POST to MSL API for skill generation."""
    from .auth import get_access_token, MSL_AUTH_URL
    from .detection import detect_all
    
    token = get_access_token()
    
    url = f"{MSL_AUTH_URL.rstrip('/')}/api/commit"
    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
        
    # Gather usage metadata
    metadata = detect_all(project_root or Path.cwd())
    
    # Convert messages to a simple text format for the commit API
    text_content = "\n".join([f"{msg['role']}: {msg['content']}" for msg in messages])
    payload = {
        "files": ["skill_generation.md"],
        "diff": text_content,
        "metadata": {
            "ide": metadata.get("ide", "Unknown"),
            "project_name": metadata.get("project_name", "Unknown"),
            "framework": metadata.get("framework", "Unknown"),
            "cli": "msl",
            "other_tools": {
                "cursor": metadata.get("cursor").installed if metadata.get("cursor") else False,
                "claude_code": metadata.get("claude-code").installed if metadata.get("claude-code") else False,
            }
        }
    }
    
    try:
        response = requests.post(url, headers=headers, json=payload, timeout=60)
        if response.status_code == 401 or response.status_code == 403:
            raise RuntimeError("Authentication failed. Please run 'msl --login' to authenticate.")
            
        response.raise_for_status()
        data = response.json()
        
        content = data.get("message", "")
        
        # For skill generation, we need a more detailed response
        if len(content) < 100:  # If it's too short, it's probably a commit message
            content = "# Generated Skill File\n\nThis is a placeholder skill file generated by MSL AI.\n\n## Instructions\n\n- Add your specific coding rules here\n- Include project-specific guidelines\n- Define your preferred coding standards"
            
        return content
    except requests.exceptions.RequestException as e:
        status_info = ""
        if hasattr(e, "response") and e.response is not None:
             status_info = f" ({e.response.status_code}: {e.response.text})"
        raise RuntimeError(f"MSL API call failed: {e}{status_info}")
    except (KeyError, ValueError) as e:
        raise RuntimeError(f"Failed to parse MSL response: {e}")


def collect_project_context(project_root: Path) -> str:
    """Read interesting files from the project to send to the LLM."""
    interesting_files = [
        "README.md",
        "package.json",
        "pyproject.toml",
        "requirements.txt",
        "Cargo.toml",
        "go.mod",
        "pubspec.yaml",
    ]

    context_parts = []
    
    for filename in interesting_files:
        path = project_root / filename
        if not path.is_file():
            continue
            
        try:
            # Read only up to MAX_FILE_BYTES to keep context window manageable
            with path.open("r", encoding="utf-8") as f:
                content = f.read(MAX_FILE_BYTES)
                if len(content) == MAX_FILE_BYTES:
                    content += "\n... (truncated)"
            
            context_parts.append(f"--- File: {filename} ---\n{content}\n")
        except OSError:
            pass

    return "\n".join(context_parts)


def build_prompt(ctx: SkillGenContext, scan: ProjectScan, project_files_text: str) -> list[dict[str, str]]:
    """Build the ChatML prompt for MSL AI."""
    
    system_prompt = (
        "You are an Elite Software Architect and AI Infrastructure Engineer. "
        "Your mission is to generate a world-class 'Skill File' (rules/instructions) for an AI coding assistant. "
        "This file will be used to guide the AI in a specific project, ensuring every line of code "
        "meets the highest industry standards for reliability, performance, and maintainability.\n\n"
        "CORE PHILOSOPHY:\n"
        "- **Pragmatic Excellence**: Solutions should be elegant but never over-engineered.\n"
        "- **Security First**: Every recommendation must consider vulnerability mitigation.\n"
        "- **Agentic Optimization**: Tailor rules so that agentic AI (like Windsurf, Cursor, or Antigravity) "
        "can use its tools and MCP servers most effectively.\n"
    )
    
    # Start building the user context message
    user_prompt_list = []
    
    user_prompt_list.append(
        f"Generate a premium AI skill file for the **{ctx.target_platform.display_name}** platform."
    )
    user_prompt_list.append(f"- **Project context**: {ctx.project_type.display_name}")
    user_prompt_list.append(f"- **Engineering Tier**: {ctx.preference_tier.display_name}")
    
    if scan.frameworks:
        user_prompt_list.append(f"- **Tech Stack**: {', '.join(scan.frameworks)}")
    
    if scan.languages:
        user_prompt_list.append(f"- **Primary Languages**: {', '.join(scan.languages)}")
        
    user_prompt_list.append("\n### SOURCE CONTEXT\n")
    if project_files_text.strip():
        user_prompt_list.append(project_files_text)
    else:
        user_prompt_list.append("(No relevant project definition files found. Use general best practices for the indicated project type.)\n")
        
    user_prompt_list.append(
        "\n### GENERATION REQUIREMENTS:\n"
        "1. **Modern Architecture**: Enforce Clean Architecture, DDD, or appropriate modern patterns. "
        "If it's Next.js, focus on the App Router and Server Components. If it's a backend, focus on type safety and service layers.\n"
        "2. **Agentic Workflows**: If the platform is Windsurf, Antigravity, or Cursor, include instructions for "
        "effective tool usage, file search strategies, and multi-step reasoning.\n"
        "3. **Visual Excellence**: For frontend projects, include rules for premium UI/UX (Tailwind best practices, "
        "accessibility, micro-animations, and responsive design).\n"
        "4. **Formatting**: Categorize the output into clear sections: `Code Style`, `Architecture`, `Data Handling`, `Security`, and `Testing`.\n"
        "5. **Constraints**: NO prose, NO greetings, NO chat. Output ONLY the raw Markdown content. "
        "Do not wrap in triple backticks if the whole response is markdown."
    )
    
    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": "\n".join(user_prompt_list)}
    ]




def generate_with_ai(
    ctx: SkillGenContext, 
    scan: ProjectScan, 
    explicit_api_key: Optional[str] = None
) -> str:
    """Orchestrates reading context, prompting MSL API, and returning the customized markdown."""
    project_files_text = collect_project_context(ctx.project_path)
    messages = build_prompt(ctx, scan, project_files_text)
    
    markdown_content = call_msl_api(messages, ctx.project_path)
    return markdown_content
