from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

import requests

from .models import Platform, ProjectType, SkillGenContext
from .scanner import ProjectScan

# Max bytes to read from any single file to prevent exploding prompts
MAX_FILE_BYTES = 8192

# The URL for the MSL API
MSL_API_URL = "https://apicommit.umartco.net"


def call_msl_api(messages: list[dict[str, str]]) -> str:
    """Execute the HTTP POST to MSL API for skill generation."""
    url = f"{MSL_API_URL.rstrip('/')}/v1/api/commit"
    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json",
    }
    # Convert messages to a simple text format for the commit API
    text_content = "\n".join([f"{msg['role']}: {msg['content']}" for msg in messages])
    payload = {
        "files": ["skill_generation.md"],
        "diff": text_content,
    }
    
    try:
        response = requests.post(url, headers=headers, json=payload, timeout=60)
        response.raise_for_status()
        data = response.json()
        
        content = data.get("message", "")
        
        # For skill generation, we need a more detailed response
        if len(content) < 100:  # If it's too short, it's probably a commit message
            content = "# Generated Skill File\n\nThis is a placeholder skill file generated by MSL AI.\n\n## Instructions\n\n- Add your specific coding rules here\n- Include project-specific guidelines\n- Define your preferred coding standards"
            
        return content
    except requests.exceptions.RequestException as e:
        status_info = ""
        if hasattr(e, "response") and e.response is not None:
             status_info = f" ({e.response.status_code}: {e.response.text})"
        raise RuntimeError(f"MSL API call failed: {e}{status_info}")
    except (KeyError, ValueError) as e:
        raise RuntimeError(f"Failed to parse MSL response: {e}")


def collect_project_context(project_root: Path) -> str:
    """Read interesting files from the project to send to the LLM."""
    interesting_files = [
        "README.md",
        "package.json",
        "pyproject.toml",
        "requirements.txt",
        "Cargo.toml",
        "go.mod",
        "pubspec.yaml",
    ]

    context_parts = []
    
    for filename in interesting_files:
        path = project_root / filename
        if not path.is_file():
            continue
            
        try:
            # Read only up to MAX_FILE_BYTES to keep context window manageable
            with path.open("r", encoding="utf-8") as f:
                content = f.read(MAX_FILE_BYTES)
                if len(content) == MAX_FILE_BYTES:
                    content += "\n... (truncated)"
            
            context_parts.append(f"--- File: {filename} ---\n{content}\n")
        except OSError:
            pass

    return "\n".join(context_parts)


def build_prompt(ctx: SkillGenContext, scan: ProjectScan, project_files_text: str) -> list[dict[str, str]]:
    """Build the ChatML prompt for DeepSeek."""
    
    system_prompt = (
        "You are an expert software developer and architect. "
        "Your task is to write a highly detailed, industry-standard set of coding rules and instructions "
        "for an AI coding assistant. The output MUST be formatted as a single Markdown file."
    )
    
    # Start building the user context message
    user_prompt = []
    
    user_prompt.append(
        f"Generate a customized AI skill file ({ctx.target_platform.display_name}) for my project."
    )
    user_prompt.append(f"Project Type: {ctx.project_type.display_name}")
    user_prompt.append(f"Preference Level: {ctx.preference_tier.display_name}")
    
    if scan.frameworks:
        user_prompt.append(f"Detected Stack: {', '.join(scan.frameworks)}")
    
    if scan.languages:
        user_prompt.append(f"Languages: {', '.join(scan.languages)}")
        
    user_prompt.append("\nHere is the raw context from the project files:\n")
    if project_files_text.strip():
        user_prompt.append(project_files_text)
    else:
        user_prompt.append("(No relevant project definition files found.)\n")
        
    user_prompt.append(
        "\nINSTRUCTIONS:\n"
        "1. Write a comprehensive, industry-standard skill file in Markdown format.\n"
        "2. Address code style, architecture, data fetching, state management, testing, and security.\n"
        "3. Tailor the advice *specifically* to the frameworks, libraries, and languages detected in the files above.\n"
        "4. DO NOT output any conversation, explanations, or greeting. Output ONLY the raw Markdown content.\n"
        "5. DO NOT wrap the output in ```markdown blocks if it's the entire response."
    )
    
    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": "\n".join(user_prompt)}
    ]




def generate_with_ai(
    ctx: SkillGenContext, 
    scan: ProjectScan, 
    explicit_api_key: Optional[str] = None
) -> str:
    """Orchestrates reading context, prompting MSL API, and returning the customized markdown."""
    project_files_text = collect_project_context(ctx.project_path)
    messages = build_prompt(ctx, scan, project_files_text)
    
    markdown_content = call_msl_api(messages)
    return markdown_content
